### ISSUE TITLE
the index.html page generated by gatsby is black

### ISSUE THREAD

**Issue by ubik76** [codebushi/gatsby-starter-dimension#6]
I have downloaded and installed Gatsby following the tutorial here: https://www.gatsbyjs.org/docs/
Then I have installed the Dimension starter.
But if I open the index.html file in the public folder, I can only see a black page.

More info here: https://stackoverflow.com/questions/50470047/cant-find-my-html-pages

Try to reproduce with the following commands:

#gatsby new gatsby-starter-dimension https://github.com/ChangoMan/gatsby-starter-dimension
#cd gatsby-starter-dimension
#gatsby develop
#gatsby build
#gatsby serve

Then try to open this file with your browser: gatsby-starter-dimension\public\index.html The page is all black.

Thank you

**Comment by fankerton** [comment]
I will make a pull request to fix this, but in the meantime the issue is in the _\src\components\Footer\index.js_ file.

```
The following 3 errors will cause the project to not compile.
  117:19  error  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank
  127:19  error  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank
  137:19  error  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank

```
To fix this, edit the Footer\index.js file and replace the rel= "noopener" with rel="noopener noreferrer" in the anchor tags.

I also had issues with a lot of the files not having the UNIX LF file endings (instead having the Windows CRLF). Which I remedied using a Sublime Text addon, I'm not 100% sure whether those were preventing the project from compiling though.

**Comment by ubik76** [comment]
can't find *\src\components\Footer\index.js*  in the repo.

The only reference I have found is here:
\gatsby-starter-dimension\node_modules\gatsby-remark-images\index.js




--
Francesco Ruffino
f.ruffino@gmail.com


2018-06-09 10:07 GMT+02:00 fankerton <notifications@github.com>:

**Comment by avocadoras** [comment]
@ubik76 just curious, why are you trying to open index.html?
